services:
  - type: web
    name: fastapi-yolo
    env: docker
    repo: https://github.com/ShlokZ/FASTAPIDEPLOYRENDERONNX.git
    branch: main
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
